/**
 * This class is generated by jOOQ
 */
package com.camel.tables;


import com.camel.tables.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Database extends SchemaImpl {

    private static final long serialVersionUID = 1404107249;

    /**
     * The reference instance of <code>database</code>
     */
    public static final Database DATABASE = new Database();

    /**
     * The table <code>database.customer</code>.
     */
    public final Customer CUSTOMER = com.camel.tables.tables.Customer.CUSTOMER;

    /**
     * The table <code>database.customer_status</code>.
     */
    public final CustomerStatus CUSTOMER_STATUS = com.camel.tables.tables.CustomerStatus.CUSTOMER_STATUS;

    /**
     * The table <code>database.project</code>.
     */
    public final Project PROJECT = com.camel.tables.tables.Project.PROJECT;

    /**
     * The table <code>database.user</code>.
     */
    public final User USER = com.camel.tables.tables.User.USER;

    /**
     * The table <code>database.user_project</code>.
     */
    public final UserProject USER_PROJECT = com.camel.tables.tables.UserProject.USER_PROJECT;

    /**
     * No further instances allowed
     */
    private Database() {
        super("database", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            CustomerStatus.CUSTOMER_STATUS,
            Project.PROJECT,
            User.USER,
            UserProject.USER_PROJECT);
    }
}
