/**
 * This class is generated by jOOQ
 */
package com.camel.tables;


import com.camel.tables.tables.Customer;
import com.camel.tables.tables.CustomerStatus;
import com.camel.tables.tables.Project;
import com.camel.tables.tables.User;
import com.camel.tables.tables.UserProject;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in database
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>database.customer</code>.
     */
    public static final Customer CUSTOMER = com.camel.tables.tables.Customer.CUSTOMER;

    /**
     * The table <code>database.customer_status</code>.
     */
    public static final CustomerStatus CUSTOMER_STATUS = com.camel.tables.tables.CustomerStatus.CUSTOMER_STATUS;

    /**
     * The table <code>database.project</code>.
     */
    public static final Project PROJECT = com.camel.tables.tables.Project.PROJECT;

    /**
     * The table <code>database.user</code>.
     */
    public static final User USER = com.camel.tables.tables.User.USER;

    /**
     * The table <code>database.user_project</code>.
     */
    public static final UserProject USER_PROJECT = com.camel.tables.tables.UserProject.USER_PROJECT;
}
