/**
 * This class is generated by jOOQ
 */
package com.camel.tables.tables;


import com.camel.tables.Database;
import com.camel.tables.Keys;
import com.camel.tables.tables.records.UserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends TableImpl<UserRecord> {

    private static final long serialVersionUID = 122078833;

    /**
     * The reference instance of <code>database.user</code>
     */
    public static final User USER = new User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRecord> getRecordType() {
        return UserRecord.class;
    }

    /**
     * The column <code>database.user.id_user</code>.
     */
    public final TableField<UserRecord, Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>database.user.firstname</code>.
     */
    public final TableField<UserRecord, String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>database.user.surname</code>.
     */
    public final TableField<UserRecord, String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>database.user.email</code>.
     */
    public final TableField<UserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * The column <code>database.user.data_create_account</code>.
     */
    public final TableField<UserRecord, Timestamp> DATA_CREATE_ACCOUNT = createField("data_create_account", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>database.user.data_modification_account</code>.
     */
    public final TableField<UserRecord, Timestamp> DATA_MODIFICATION_ACCOUNT = createField("data_modification_account", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>database.user.status</code>.
     */
    public final TableField<UserRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * Create a <code>database.user</code> table reference
     */
    public User() {
        this("user", null);
    }

    /**
     * Create an aliased <code>database.user</code> table reference
     */
    public User(String alias) {
        this(alias, USER);
    }

    private User(String alias, Table<UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private User(String alias, Table<UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Database.DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserRecord> getPrimaryKey() {
        return Keys.KEY_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRecord>>asList(Keys.KEY_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User as(String alias) {
        return new User(alias, this);
    }

    /**
     * Rename this table
     */
    public User rename(String name) {
        return new User(name, null);
    }
}
